class_name EnvironmentSampler
extends RefCounted

const SAMPLE_EPSILON: float = 0.000001
const STANDARD_ATMOSPHERE_DEPTH_METERS: float = 10.06

var _snapshot: EnvironmentGenerationSnapshot

var _temperature_noise: FastNoiseLite
var _current_primary_noise: FastNoiseLite
var _current_detail_noise: FastNoiseLite
var _nutrient_noise: FastNoiseLite


func _init(
	generation_snapshot: EnvironmentGenerationSnapshot
) -> void:
	assert(generation_snapshot != null)

	_snapshot = generation_snapshot

	_temperature_noise = _create_noise(
		EnvironmentChannels.REGIONAL_TEMPERATURE,
		_snapshot.regional_temperature_frequency
	)

	_current_primary_noise = _create_noise(
		EnvironmentChannels.CURRENT_PRIMARY,
		_snapshot.current_primary_frequency
	)

	_current_detail_noise = _create_noise(
		EnvironmentChannels.CURRENT_DETAIL,
		_snapshot.current_detail_frequency
	)

	_nutrient_noise = _create_noise(
		EnvironmentChannels.NUTRIENT_VARIATION,
		_snapshot.nutrient_variation_frequency
	)


## Samples an exact interior terrain-grid vertex using a centered
## 3 × 3 terrain neighborhood.
##
## Chunk-edge vertices return null because centered derivatives require
## authoritative samples from the adjacent chunk.
func sample_interior(
	terrain_data: TerrainChunkData,
	local_sample_x: int,
	local_sample_z: int
) -> EnvironmentSample:
	if not _validate_terrain_data(terrain_data):
		return null

	var cells_per_axis := terrain_data.cells_per_axis
	var samples_per_axis := cells_per_axis + 1

	if (
		local_sample_x <= 0
		or local_sample_z <= 0
		or local_sample_x >= cells_per_axis
		or local_sample_z >= cells_per_axis
	):
		return null

	var center_index := _get_index(
		local_sample_x,
		local_sample_z,
		samples_per_axis
	)

	var left_index := _get_index(
		local_sample_x - 1,
		local_sample_z,
		samples_per_axis
	)

	var right_index := _get_index(
		local_sample_x + 1,
		local_sample_z,
		samples_per_axis
	)

	var upper_index := _get_index(
		local_sample_x,
		local_sample_z - 1,
		samples_per_axis
	)

	var lower_index := _get_index(
		local_sample_x,
		local_sample_z + 1,
		samples_per_axis
	)

	var center_height := (
		terrain_data.height_values[center_index]
	)

	var left_height := (
		terrain_data.height_values[left_index]
	)

	var right_height := (
		terrain_data.height_values[right_index]
	)

	var upper_height := (
		terrain_data.height_values[upper_index]
	)

	var lower_height := (
		terrain_data.height_values[lower_index]
	)

	var cell_size := terrain_data.cell_size

	var gradient_x := (
		(right_height - left_height)
		/ (2.0 * cell_size)
	)

	var gradient_z := (
		(lower_height - upper_height)
		/ (2.0 * cell_size)
	)

	var slope_degrees := _calculate_slope_degrees(
		gradient_x,
		gradient_z
	)

	var roughness_meters := _calculate_vertex_roughness(
		terrain_data.height_values,
		local_sample_x,
		local_sample_z,
		samples_per_axis,
		cell_size,
		center_height,
		gradient_x,
		gradient_z
	)

	var geology_data := terrain_data.geology_data

	var world_xz := (
		geology_data.world_origin
		+ Vector2(
			float(local_sample_x) * cell_size,
			float(local_sample_z) * cell_size
		)
	)

	return _create_sample(
		world_xz,
		center_height,
		geology_data.macro_elevation[center_index],
		slope_degrees,
		roughness_meters,
		geology_data.volcanic_potential[center_index],
		geology_data.sediment_potential[center_index],
		geology_data.ridge_potential[center_index],
		geology_data.trench_potential[center_index],
		int(geology_data.trench_tiers[center_index]),
		geology_data.compression_strength[center_index],
		geology_data.extension_strength[center_index],
		geology_data.shear_strength[center_index],
		geology_data.convergent_potential[center_index],
		geology_data.shallow_province_influence[
			center_index
		],
		geology_data.deep_province_influence[
			center_index
		],
		geology_data.abyssal_province_influence[
			center_index
		],
		geology_data.province_transition_influence[
			center_index
		]
	)


## Samples an arbitrary world-space point from already-generated
## TerrainChunkData.
##
## The chunk domain is half-open:
##
##     [world_origin, world_origin + chunk_size)
##
## The minimum X/Z edges belong to this chunk. The maximum X/Z edges
## belong to the adjacent positive-axis chunks. This removes ambiguity
## at shared chunk borders.
##
## No terrain or geology is generated by this method.
func sample_world(
	terrain_data: TerrainChunkData,
	world_xz: Vector2
) -> EnvironmentSample:
	if not _validate_terrain_data(terrain_data):
		return null

	if (
		not is_finite(world_xz.x)
		or not is_finite(world_xz.y)
	):
		return null

	var geology_data := terrain_data.geology_data
	var world_origin := geology_data.world_origin

	var local_xz := (
		world_xz
		- world_origin
	)

	var chunk_size := (
		float(terrain_data.cells_per_axis)
		* terrain_data.cell_size
	)

	## Half-open ownership prevents two chunks from answering for the
	## same position with different local derivative cells.
	if (
		local_xz.x < 0.0
		or local_xz.y < 0.0
		or local_xz.x >= chunk_size
		or local_xz.y >= chunk_size
	):
		return null

	var cells_per_axis := terrain_data.cells_per_axis
	var samples_per_axis := cells_per_axis + 1
	var cell_size := terrain_data.cell_size

	var continuous_cell_x := (
		local_xz.x
		/ cell_size
	)

	var continuous_cell_z := (
		local_xz.y
		/ cell_size
	)

	var cell_x := clampi(
		floori(continuous_cell_x),
		0,
		cells_per_axis - 1
	)

	var cell_z := clampi(
		floori(continuous_cell_z),
		0,
		cells_per_axis - 1
	)

	var factor_x := clampf(
		continuous_cell_x
		- float(cell_x),
		0.0,
		1.0
	)

	var factor_z := clampf(
		continuous_cell_z
		- float(cell_z),
		0.0,
		1.0
	)

	var index_00 := _get_index(
		cell_x,
		cell_z,
		samples_per_axis
	)

	var index_10 := _get_index(
		cell_x + 1,
		cell_z,
		samples_per_axis
	)

	var index_01 := _get_index(
		cell_x,
		cell_z + 1,
		samples_per_axis
	)

	var index_11 := _get_index(
		cell_x + 1,
		cell_z + 1,
		samples_per_axis
	)

	var height_00 := terrain_data.height_values[index_00]
	var height_10 := terrain_data.height_values[index_10]
	var height_01 := terrain_data.height_values[index_01]
	var height_11 := terrain_data.height_values[index_11]

	var seabed_elevation := _bilerp_values(
		height_00,
		height_10,
		height_01,
		height_11,
		factor_x,
		factor_z
	)

	## Partial derivatives of the bilinear terrain patch.
	var gradient_x := (
		lerpf(
			height_10 - height_00,
			height_11 - height_01,
			factor_z
		)
		/ cell_size
	)

	var gradient_z := (
		lerpf(
			height_01 - height_00,
			height_11 - height_10,
			factor_x
		)
		/ cell_size
	)

	var slope_degrees := _calculate_slope_degrees(
		gradient_x,
		gradient_z
	)

	## The bilinear interaction term is zero for a planar cell. Its
	## quarter magnitude equals the RMS residual of the four corners
	## from their best additive plane.
	var bilinear_twist := (
		height_00
		- height_10
		- height_01
		+ height_11
	)

	var roughness_meters := (
		absf(bilinear_twist)
		* 0.25
	)

	var macro_elevation := _bilerp_channel(
		geology_data.macro_elevation,
		index_00,
		index_10,
		index_01,
		index_11,
		factor_x,
		factor_z
	)

	var volcanic_potential := _bilerp_channel(
		geology_data.volcanic_potential,
		index_00,
		index_10,
		index_01,
		index_11,
		factor_x,
		factor_z
	)

	var sediment_potential := _bilerp_channel(
		geology_data.sediment_potential,
		index_00,
		index_10,
		index_01,
		index_11,
		factor_x,
		factor_z
	)

	var ridge_potential := _bilerp_channel(
		geology_data.ridge_potential,
		index_00,
		index_10,
		index_01,
		index_11,
		factor_x,
		factor_z
	)

	var trench_potential := _bilerp_channel(
		geology_data.trench_potential,
		index_00,
		index_10,
		index_01,
		index_11,
		factor_x,
		factor_z
	)

	var compression_strength := _bilerp_channel(
		geology_data.compression_strength,
		index_00,
		index_10,
		index_01,
		index_11,
		factor_x,
		factor_z
	)

	var extension_strength := _bilerp_channel(
		geology_data.extension_strength,
		index_00,
		index_10,
		index_01,
		index_11,
		factor_x,
		factor_z
	)

	var shear_strength := _bilerp_channel(
		geology_data.shear_strength,
		index_00,
		index_10,
		index_01,
		index_11,
		factor_x,
		factor_z
	)

	var convergent_potential := _bilerp_channel(
		geology_data.convergent_potential,
		index_00,
		index_10,
		index_01,
		index_11,
		factor_x,
		factor_z
	)

	var shallow_influence := _bilerp_channel(
		geology_data.shallow_province_influence,
		index_00,
		index_10,
		index_01,
		index_11,
		factor_x,
		factor_z
	)

	var deep_influence := _bilerp_channel(
		geology_data.deep_province_influence,
		index_00,
		index_10,
		index_01,
		index_11,
		factor_x,
		factor_z
	)

	var abyssal_influence := _bilerp_channel(
		geology_data.abyssal_province_influence,
		index_00,
		index_10,
		index_01,
		index_11,
		factor_x,
		factor_z
	)

	var transition_influence := _bilerp_channel(
		geology_data.province_transition_influence,
		index_00,
		index_10,
		index_01,
		index_11,
		factor_x,
		factor_z
	)

	var trench_tier := _select_trench_tier(
		geology_data,
		index_00,
		index_10,
		index_01,
		index_11,
		factor_x,
		factor_z
	)

	return _create_sample(
		world_xz,
		seabed_elevation,
		macro_elevation,
		slope_degrees,
		roughness_meters,
		volcanic_potential,
		sediment_potential,
		ridge_potential,
		trench_potential,
		trench_tier,
		compression_strength,
		extension_strength,
		shear_strength,
		convergent_potential,
		shallow_influence,
		deep_influence,
		abyssal_influence,
		transition_influence
	)


func _create_sample(
	world_xz: Vector2,
	seabed_elevation: float,
	macro_elevation: float,
	slope_degrees: float,
	roughness_meters: float,
	volcanic_value: float,
	sediment_value: float,
	ridge_value: float,
	trench_value: float,
	trench_tier: int,
	compression_value: float,
	extension_value: float,
	shear_value: float,
	convergent_value: float,
	shallow_value: float,
	deep_value: float,
	abyssal_value: float,
	transition_value: float
) -> EnvironmentSample:
	var slope_strength := _smoothstep(
		0.0,
		_snapshot.full_rock_slope_degrees,
		slope_degrees
	)

	var roughness_strength := _smoothstep(
		0.0,
		_snapshot.full_roughness_meters,
		roughness_meters
	)

	var depth_below_surface := maxf(
		_snapshot.ocean_height
		- seabed_elevation,
		0.0
	)

	var micro_elevation := (
		seabed_elevation
		- macro_elevation
	)

	var light_availability := clampf(
		exp(
			-depth_below_surface
			* _snapshot.light_attenuation
		),
		0.0,
		1.0
	)

	var pressure_atmospheres := (
		1.0
		+ depth_below_surface
		/ STANDARD_ATMOSPHERE_DEPTH_METERS
	)

	var volcanic_potential := clampf(
		volcanic_value,
		0.0,
		1.0
	)

	var sediment_potential := clampf(
		sediment_value,
		0.0,
		1.0
	)

	var ridge_potential := clampf(
		ridge_value,
		0.0,
		1.0
	)

	var trench_potential := clampf(
		trench_value,
		0.0,
		1.0
	)

	var compression_strength := clampf(
		compression_value,
		0.0,
		1.0
	)

	var extension_strength := clampf(
		extension_value,
		0.0,
		1.0
	)

	var shear_strength := clampf(
		shear_value,
		0.0,
		1.0
	)

	var convergent_potential := clampf(
		convergent_value,
		0.0,
		1.0
	)

	var geological_activity := maxf(
		volcanic_potential,
		maxf(
			ridge_potential,
			maxf(
				trench_potential,
				maxf(
					convergent_potential,
					shear_strength
				)
			)
		)
	)

	var geological_stability := clampf(
		1.0 - geological_activity,
		0.0,
		1.0
	)

	var regional_temperature_value := (
		_temperature_noise.get_noise_2d(
			world_xz.x,
			world_xz.y
		)
	)

	var regional_surface_temperature := (
		_snapshot.surface_temperature_celsius
		+ regional_temperature_value
		* _snapshot.regional_temperature_variation
	)

	var cooled_temperature := maxf(
		_snapshot.minimum_deep_temperature_celsius,
		regional_surface_temperature
		- depth_below_surface
		* _snapshot.depth_cooling_per_meter
	)

	var geothermal_energy := maxf(
		volcanic_potential,
		maxf(
			ridge_potential,
			trench_potential * 0.70
		)
	)

	var temperature_celsius := clampf(
		cooled_temperature
		+ geothermal_energy
		* _snapshot.geothermal_temperature_increase,
		-10.0,
		60.0
	)

	var current_primary := _unit_noise(
		_current_primary_noise,
		world_xz
	)

	var current_detail := _unit_noise(
		_current_detail_noise,
		world_xz
	)

	var current_exposure := clampf(
		(
			current_primary * 0.72
			+ current_detail * 0.28
		)
		* (
			0.80
			+ slope_strength * 0.20
		),
		0.0,
		1.0
	)

	var regional_nutrients := _unit_noise(
		_nutrient_noise,
		world_xz
	)

	var nutrient_potential := clampf(
		0.08
		+ regional_nutrients * 0.22
		+ sediment_potential * 0.25
		+ current_exposure * 0.18
		+ geothermal_energy * 0.35,
		0.0,
		1.0
	)

	var shallow_influence := clampf(
		shallow_value,
		0.0,
		1.0
	)

	var deep_influence := clampf(
		deep_value,
		0.0,
		1.0
	)

	var abyssal_influence := clampf(
		abyssal_value,
		0.0,
		1.0
	)

	var province_total := (
		shallow_influence
		+ deep_influence
		+ abyssal_influence
	)

	if province_total <= SAMPLE_EPSILON:
		shallow_influence = 1.0
		deep_influence = 0.0
		abyssal_influence = 0.0
	else:
		shallow_influence /= province_total
		deep_influence /= province_total
		abyssal_influence /= province_total

	var transition_influence := clampf(
		transition_value,
		0.0,
		1.0
	)

	var low_slope := 1.0 - slope_strength
	var low_roughness := 1.0 - roughness_strength

	var rock_weight := maxf(
		SAMPLE_EPSILON,
		0.08
		+ slope_strength * 0.55
		+ roughness_strength * 0.30
		+ volcanic_potential * 0.35
		+ ridge_potential * 0.25
		+ trench_potential * 0.20
	)

	var sand_weight := maxf(
		SAMPLE_EPSILON,
		0.06
		+ sediment_potential
		* low_slope
		* (
			0.75
			- abyssal_influence * 0.30
		)
	)

	var soft_sediment_weight := maxf(
		SAMPLE_EPSILON,
		0.04
		+ sediment_potential
		* low_slope
		* low_roughness
		* (
			0.35
			+ abyssal_influence * 0.65
		)
	)

	var substrate_total := (
		rock_weight
		+ sand_weight
		+ soft_sediment_weight
	)

	var rock_substrate := (
		rock_weight
		/ substrate_total
	)

	var sand_substrate := (
		sand_weight
		/ substrate_total
	)

	var soft_sediment_substrate := (
		soft_sediment_weight
		/ substrate_total
	)

	var photic_productivity := (
		light_availability
		* nutrient_potential
		* (
			0.45
			+ geological_stability * 0.55
		)
	)

	var chemosynthetic_productivity := (
		geothermal_energy
		* nutrient_potential
		* (
			0.40
			+ rock_substrate * 0.60
		)
	)

	var biological_potential := clampf(
		maxf(
			photic_productivity,
			chemosynthetic_productivity
		),
		0.0,
		1.0
	)

	return EnvironmentSample.new(
		world_xz,
		seabed_elevation,
		depth_below_surface,
		macro_elevation,
		micro_elevation,
		slope_degrees,
		slope_strength,
		roughness_meters,
		roughness_strength,
		light_availability,
		temperature_celsius,
		pressure_atmospheres,
		nutrient_potential,
		current_exposure,
		geological_stability,
		volcanic_potential,
		sediment_potential,
		ridge_potential,
		trench_potential,
		trench_tier,
		compression_strength,
		extension_strength,
		shear_strength,
		shallow_influence,
		deep_influence,
		abyssal_influence,
		transition_influence,
		rock_substrate,
		sand_substrate,
		soft_sediment_substrate,
		biological_potential
	)


func _validate_terrain_data(
	terrain_data: TerrainChunkData
) -> bool:
	if terrain_data == null:
		return false

	if _snapshot == null:
		return false

	if not _snapshot.get_validation_error().is_empty():
		return false

	if (
		terrain_data.cells_per_axis < 1
		or not is_finite(terrain_data.cell_size)
		or terrain_data.cell_size <= 0.0
	):
		return false

	var samples_per_axis := (
		terrain_data.cells_per_axis + 1
	)

	var expected_sample_count := (
		samples_per_axis
		* samples_per_axis
	)

	if (
		terrain_data.height_values.size()
		!= expected_sample_count
	):
		return false

	var geology_data := terrain_data.geology_data

	if geology_data == null:
		return false

	return _has_required_geology_channels(
		geology_data,
		expected_sample_count
	)


func _has_required_geology_channels(
	data: GeologyChunkData,
	expected_size: int
) -> bool:
	return (
		data.macro_elevation.size() == expected_size
		and data.volcanic_potential.size() == expected_size
		and data.sediment_potential.size() == expected_size
		and data.ridge_potential.size() == expected_size
		and data.trench_potential.size() == expected_size
		and data.trench_tiers.size() == expected_size
		and data.compression_strength.size() == expected_size
		and data.extension_strength.size() == expected_size
		and data.shear_strength.size() == expected_size
		and data.convergent_potential.size() == expected_size
		and data.shallow_province_influence.size()
			== expected_size
		and data.deep_province_influence.size()
			== expected_size
		and data.abyssal_province_influence.size()
			== expected_size
		and data.province_transition_influence.size()
			== expected_size
	)


func _calculate_vertex_roughness(
	height_values: PackedFloat32Array,
	center_x: int,
	center_z: int,
	samples_per_axis: int,
	cell_size: float,
	center_height: float,
	gradient_x: float,
	gradient_z: float
) -> float:
	var squared_residual_sum := 0.0
	var sample_count := 0

	for offset_z in range(-1, 2):
		for offset_x in range(-1, 2):
			if offset_x == 0 and offset_z == 0:
				continue

			var sample_index := _get_index(
				center_x + offset_x,
				center_z + offset_z,
				samples_per_axis
			)

			var predicted_height := (
				center_height
				+ gradient_x
				* float(offset_x)
				* cell_size
				+ gradient_z
				* float(offset_z)
				* cell_size
			)

			var residual := (
				height_values[sample_index]
				- predicted_height
			)

			squared_residual_sum += (
				residual * residual
			)

			sample_count += 1

	if sample_count < 1:
		return 0.0

	return sqrt(
		squared_residual_sum
		/ float(sample_count)
	)


func _select_trench_tier(
	data: GeologyChunkData,
	index_00: int,
	index_10: int,
	index_01: int,
	index_11: int,
	factor_x: float,
	factor_z: float
) -> int:
	var inverse_x := 1.0 - factor_x
	var inverse_z := 1.0 - factor_z

	var weight_00 := inverse_x * inverse_z
	var weight_10 := factor_x * inverse_z
	var weight_01 := inverse_x * factor_z
	var weight_11 := factor_x * factor_z

	var indices: Array[int] = [
		index_00,
		index_10,
		index_01,
		index_11
	]

	var weights: Array[float] = [
		weight_00,
		weight_10,
		weight_01,
		weight_11
	]

	var selected_tier := (
		GeologyChunkData.TRENCH_TIER_NONE
	)

	var strongest_score := 0.0

	for corner in range(4):
		var sample_index := indices[corner]

		var score := (
			weights[corner]
			* clampf(
				data.trench_potential[sample_index],
				0.0,
				1.0
			)
		)

		if score > strongest_score:
			strongest_score = score
			selected_tier = int(
				data.trench_tiers[sample_index]
			)

	if strongest_score <= SAMPLE_EPSILON:
		return GeologyChunkData.TRENCH_TIER_NONE

	return selected_tier


func _create_noise(
	channel_id: int,
	frequency: float
) -> FastNoiseLite:
	var noise := FastNoiseLite.new()

	noise.seed = StableSeed.derive_channel_seed(
		_snapshot.environment_seed,
		channel_id
	)

	noise.frequency = frequency
	noise.noise_type = FastNoiseLite.TYPE_SIMPLEX_SMOOTH
	noise.fractal_type = FastNoiseLite.FRACTAL_NONE

	return noise


static func _bilerp_channel(
	values: PackedFloat32Array,
	index_00: int,
	index_10: int,
	index_01: int,
	index_11: int,
	factor_x: float,
	factor_z: float
) -> float:
	return _bilerp_values(
		values[index_00],
		values[index_10],
		values[index_01],
		values[index_11],
		factor_x,
		factor_z
	)


static func _bilerp_values(
	value_00: float,
	value_10: float,
	value_01: float,
	value_11: float,
	factor_x: float,
	factor_z: float
) -> float:
	var upper_value := lerpf(
		value_00,
		value_10,
		factor_x
	)

	var lower_value := lerpf(
		value_01,
		value_11,
		factor_x
	)

	return lerpf(
		upper_value,
		lower_value,
		factor_z
	)


static func _calculate_slope_degrees(
	gradient_x: float,
	gradient_z: float
) -> float:
	var gradient_magnitude := sqrt(
		gradient_x * gradient_x
		+ gradient_z * gradient_z
	)

	return rad_to_deg(
		atan(gradient_magnitude)
	)


static func _unit_noise(
	noise: FastNoiseLite,
	world_xz: Vector2
) -> float:
	return clampf(
		noise.get_noise_2d(
			world_xz.x,
			world_xz.y
		) * 0.5 + 0.5,
		0.0,
		1.0
	)


static func _get_index(
	local_x: int,
	local_z: int,
	samples_per_axis: int
) -> int:
	return (
		local_z * samples_per_axis
		+ local_x
	)


static func _smoothstep(
	edge_zero: float,
	edge_one: float,
	value: float
) -> float:
	if is_equal_approx(edge_zero, edge_one):
		return 0.0

	var factor := clampf(
		(value - edge_zero)
		/ (edge_one - edge_zero),
		0.0,
		1.0
	)

	return (
		factor
		* factor
		* (3.0 - 2.0 * factor)
	)
